


train_resnet18_opt = {"datasets":None,
        "half":False,
        "copy":None,
        "check_point":None,
        "device":"auto",
        "task_version":'cn_resnet18_decoder',# "yubo_with_pub_reconver_resnet18",
        "exp_name":"exp_ori",
        "train_aug_expend_ratio":2.5,
        "train_ratio":0.7,
        "val_ratio":0.2,
        "model":'cn_resnet18_decoder',
        "smooth_loss":False,
        "loss_alpha":0.2,
        "loss_beta":0.5,
        "loss_theta":1,
        'debug':False,
        "input_width":512,
        "input_height":512,
        "input_channels":3,
        "train_batch_size":16,
        "val_batch_size":16,
        "epoches":500}


train_omnipose_mod_mult_2stage_after_wh = {"datasets":None,
        "half":False,
        "copy":None,# copy_src_model,
        "check_point":None,
        "device":"auto",
        "task_version":"ywbr_omnipose_mod_half_2stage_after_wh",# "yubo_with_pub_reconver_resnet18",
        "exp_name":"exp_ori",
        "train_aug_expend_ratio":2.5,
        "train_ratio":0.7,
        "val_ratio":0.2,
        "model":"omnipose_mod_2stage",
        "smooth_loss":False,
        "loss_alpha":0.2,
        "loss_beta":0.5,
        "loss_theta":1,
        "input_width":512,
        "input_height":512,
        "input_channels":3,
        "train_batch_size":16,
        "val_batch_size":16,
        "epoches":500,
        "debug":False}# exp_ori_wh_cylinder1


train_hrnet_mod_mult_2stage_exp_ori_512_opt = {"datasets":None,
        "half":False,
        "copy":None,# copy_src_model,
        "check_point":None,
        "device":"auto",
        "task_version":"hrnet_mod_2tage_exp_ori",# "yubo_with_pub_reconver_resnet18",
        "exp_name":"exp_ori",
        "train_aug_expend_ratio":2.5,
        "train_ratio":0.7,
        "val_ratio":0.2,
        "model":"hrnet_mod_2stage",
        "smooth_loss":False,
        "loss_alpha":0.2,
        "loss_beta":0.5,
        "loss_theta":1,
        "input_width":512,
        "input_height":512,
        "input_channels":3,
        "train_batch_size":16,
        "val_batch_size":16,
        "epoches":500,
        "debug":False}

train_resnet50_opt = {"datasets":None,
        "half":False,
        "copy":None,
        "check_point":None,
        "device":"auto",
        "task_version":'cn_resnet50_decoder',# "yubo_with_pub_reconver_resnet18",
        "exp_name":"exp_ori",
        "train_aug_expend_ratio":2.5,
        "train_ratio":0.7,
        "val_ratio":0.2,
        "model":'cn_resnet50_decoder',
        "smooth_loss":False,
        "loss_alpha":0.2,
        "loss_beta":0.5,
        "loss_theta":1,
        'debug':False,
        "input_width":512,
        "input_height":512,
        "input_channels":3,
        "train_batch_size":16,
        "val_batch_size":16,
        "epoches":500}

train_omnipose_mobilenetv2 = {"datasets":None,
        "half":False,
        "copy":None,# copy_src_model,
        "check_point":None,
        "device":"auto",
        "task_version":"mobilenetv2_oripose",# "yubo_with_pub_reconver_resnet18",
        "exp_name":"exp_ori",
        "train_aug_expend_ratio":2.5,
        "train_ratio":0.7,
        "val_ratio":0.2,
        "model":"mobilenetv2_decoder",
        "smooth_loss":False,
        "loss_alpha":0.2,
        "loss_beta":0.5,
        "loss_theta":1,
        "input_width":512,
        "input_height":512,
        "input_channels":3,
        "train_batch_size":16,
        "val_batch_size":16,
        "epoches":500,
        "debug":False}# exp_ori_wh_cylinder1

train_omnipose_shufflenet = {"datasets":None,
        "half":False,
        "copy":None,# copy_src_model,
        "check_point":None,
        "device":"cuda:1",
        "task_version":"shufflenet_oripose",# "yubo_with_pub_reconver_resnet18",
        "exp_name":"exp_ori",
        "train_aug_expend_ratio":2.5,
        "train_ratio":0.7,
        "val_ratio":0.2,
        "model":"shufflenet_decoder",
        "smooth_loss":False,
        "loss_alpha":0.2,
        "loss_beta":0.5,
        "loss_theta":1,
        "input_width":512,
        "input_height":512,
        "input_channels":3,
        "train_batch_size":32,
        "val_batch_size":32,
        "epoches":500,
        "debug":False}# exp_ori_wh_cylinder1

